default_environment: dev
project_id: 01a0f117-9024-7440-8cc4-6bc9877071fe
environments:
- name: dev
- name: staging
- name: prod
python: python3.11
plugins:
  extractors:
  - name: tap-postgres
    variant: meltanolabs
    pip_url: meltanolabs-tap-postgres
    config:
      database: postgres
      filter_schemas:
      - public
      host: aws-0-ap-southeast-1.pooler.supabase.com
      port: 5432
      user: postgres.kiaqzmzkmabudmgmoxas
    select:
    - public-resale_flat_prices_from_jan_2017.*
  loaders:
  - name: target-bigquery
    variant: z3z1ma
    pip_url: git+https://github.com/z3z1ma/target-bigquery.git setuptools<80
    config:
      batch_size: 104857600
      credentials_path: /home/eric/NTU_DSAI/augmented-slice-482513-g2-371c6d634c40.json
      dataset: resale
      denormalized: true
      flattening_enabled: true
      flattening_max_depth: 1
      method: batch_job
      project: augmented-slice-482513-g2
